[package]
name = "rodbus"
version = "0.1.1"
authors = ["Adam Crain <jadamcrain@automatak.com>", "Émile Grégoire <emile@automatak.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "A high-performance implementation of the Modbus protocol using Tokio and async/await"
keywords = ["modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://www.github.com/automatak/rodbus"
readme = "../README.md"

[badges]
codecov = { repository = "automatak/rodbus", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
tokio = { version = "0.3", features = ["net", "sync", "io-util", "time", "rt", "rt-multi-thread", "macros"]}
log = "0.4"
no-panic = { version = "0.1", optional = true }

[dev-dependencies]
tokio-test = "0.3"
simple_logger = "1.9"